[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
# base =

primaryColor = "#62c07f"  # "#66FCF1"
# Background color for the main content area.
backgroundColor = "#2F3132"
# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#1B1E1E"
# Color used for almost all text.
textColor = "#FCFCFC"